### ISSUE TITLE
Program doesn't terminate when invoking one of the suspend library functions

### ISSUE THREAD

**Issue by cypressious** [gildor/kotlin-coroutines-retrofit#14] opened 2017-05-15 19:04 UTC
This program doesn't terminate

```kotlin
fun main(args: Array<String>) = runBlocking(CommonPool) {
    val result = service.someCall().awaitResponse()
    println(result) 
}
```

**Comment by gildor** [comment] 2017-05-15 19:44
I've tried and I see no issue:
https://gist.github.com/gildor/aa2b2f23ffbc963e3bde2f180150cc07

Could you reproduce this issue and share code?
The only possible reason that I see it's some exceptions in your OkHttp interceptor or Retrofit adapter factory, I just not sure that in this case, coroutine getting callbacks

**Comment by cypressious** [comment] 2017-05-15 20:03
When I build and run the project in https://gist.github.com/anonymous/e13969100d35b778986db6bf7fb2275f, the app doesn't terminate.

**Comment by cypressious** [comment] 2017-05-15 20:10
I'm sorry, the gist is a bit messy, you can compile the project from these sources

[KotlinDesktopPlayground.zip](https://github.com/gildor/kotlin-coroutines-retrofit/files/1002331/KotlinDesktopPlayground.zip)

**Comment by gildor** [comment] 2017-05-15 20:14
Yes, I see that if I use gradle application plugin and `run` task.
Looks like some thread still alive, even after coroutines finished. I will investigate this

**Comment by gildor** [comment] 2017-06-18 15:20
@cypressious The reason of that behavior `Executors.newCachedThreadPool()` that used as default executor for Retrofit2 (except cases when you run request synchronously).
According to [docs](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newCachedThreadPool()) threads of CachedThreadPool wait 60 seconds before shutdown.
So I see only one way: set custom Executor to OkHttpClient and shutdown it manually or create executor that creates daemon threads.

**Comment by gildor** [comment] 2017-06-27 09:21
@cypressious I'm closing this issue. if you have some other ideas please reopen with your comment

**Closed by gildor** 2017-06-27 09:21 UTC
